# Site settings
title: "Technology crap dug up from the interwebs"
description: "Random tech finds and discoveries"
author: ""
url: "https://marduk191.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:title/

# Collections
collections:
  tags:
    output: true
    permalink: /category/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "category"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - preview.html
  - _templates
